### ISSUE TITLE
Indien 318: {māca}m

### ISSUE THREAD

**Issue by chchch** [TST-Project/mss#20]
Not sure if this is a typo for {mācam} or if it indicates that "m" is written, an abbreviation of "mācam".

**Comment by manufrancis** [comment]
Not a typo. It seems we have the abbreviation for _mācam_ followed by _m_, which I thus transliterate _{māca}m_.
NB: I have here used, following DHARMA EGD, the `@reason="eccentric_ductus"` with `<unclear>` as I found {mācam}/{māca} was not very claerly written. Is it OK?
