### ISSUE TITLE
Codicological unit display

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#28]
See e.g.

![image](https://user-images.githubusercontent.com/905870/117821518-f82ee600-b26b-11eb-8e5b-3776ba3465b4.png)

We should have "u3" (lower case) and not "U3" (upper case).

**Comment by chchch** [comment]
I think this depends on whether you typed U3 or u3?

**Comment by manufrancis** [comment]
Oops, this is Indien 462.

And I have typed "u3".

![image](https://user-images.githubusercontent.com/905870/117822895-3678d500-b26d-11eb-8c19-49ed33f613f3.png)

Which is correctly displayed "u3" in Contents and Text transcription but not yet in Scribal Hands

![image](https://user-images.githubusercontent.com/905870/117823111-688a3700-b26d-11eb-90ed-976de419e865.png)

**Comment by chchch** [comment]
Oops, fixed!
