### ISSUE TITLE
Display implementation

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#31]
Could you align with DHARMA display the following:
*`<unclear>pi</unclear>` = (pi) [not italicised; parentheses in red]
*`<supplied reason="lost OR illegible">pi</supplied>` = [pi] [not italicised; parentheses in red]
NB: can you change the value "damaged" of @reason to "lost"?
*`<supplied reason="omitted">pi</supplied>` = ⟨pi⟩ [not italicised; parentheses in red]
*`<surplus>pi</surplus>` = {pi} [not italicised; parentheses in red]

**Comment by chchch** [comment]
Done! Check if `<choice><unclear></unclear></choice>` looks the way that you intend (in that case, brackets are placed around `<choice/>`, not `<unclear/>`).
