### ISSUE TITLE
Display of <orig> and <sic>

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#32]
*`<orig>ri</orig>` [unstandard] = ¡dharma! [not italicised; ¡ and ! in red]
*`<sic>ri</sic>` [incorrect] = ¿dharma? [not italicised; ¿ and ? in red]
In case these are used inside `<choice>`
e.g.
`<choice><orig>ri</orig><reg>ṟi</reg></choice>`
`<choice><sic>ki</sic><corr>ti</corr></choice>`
would it be possible/easy to have the same display for `<orig>` and `<sic>` and to have the `<reg>` and `<corr>` content in tool-tip mouse-over?

**Comment by chchch** [comment]
Done!

**Comment by manufrancis** [comment]
Could you for `<reg>` add inverted exclamation mark before? (like we have inverted question mark before, for `<sic>`)

![image](https://user-images.githubusercontent.com/905870/118941060-a106d080-b951-11eb-9667-8a56e9bccff8.png)

**Comment by chchch** [comment]
Oops, there was a typo in the style sheet. Fixed!
