### ISSUE TITLE
Double <unclear> within <choice>

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#34]
`<choice><unclear reason="vowel_unclear">ki</unclear><unclear reason="vowel_unclear">kī</unclear></choice>`
Currently displayed
![image](https://user-images.githubusercontent.com/905870/118821467-90a21780-b8b7-11eb-85e4-256622a80de6.png)

Could you make it
(ki/kī) [add slash; parentheses and slash in red]

**Comment by chchch** [comment]
Fixed!
