### ISSUE TITLE
Decoration/Types

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#35]
Add "cypher" for e.g. royal cypher such as:

![image](https://user-images.githubusercontent.com/905870/119473881-e4937d00-bd4b-11eb-9f2a-9e8ea811a96e.png)

**Comment by chchch** [comment]
Done! (Should we make it more specific as "royal cypher" or more general as "monogram"? "Cypher" now has the meaning of something like "cryptogram"...)

**Comment by manufrancis** [comment]
OK, let us go for "mogramm".
I was guided/mislead by Wikipedia ;-)

**Comment by chchch** [comment]
Oh wait... apparently a monogram and a royal cypher are slightly different, according to Wikipedia. a monogram is a combination of two or more letters, while a royal cypher doesn't combine letters?

**Comment by manufrancis** [comment]
Hmm hmm ... Let us ponder ...
