### ISSUE TITLE
<placeName> tag

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#40]
`<placeName xml:lang="ta">Tiruvaṇṇāmalai</placeName>` is not currently displayed in Tamil characters, when pushing the magic button 
![image](https://user-images.githubusercontent.com/905870/119476880-c3805b80-bd4e-11eb-8f7c-f301d0ad0172.png)

See e.g. Indien 298, summary.

**Comment by chchch** [comment]
Fixed!
