### ISSUE TITLE
Grantha display

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#46]
Currently
 
`tākavu=<seg rend="grantha">m</seg>`
is displayed
![image](https://user-images.githubusercontent.com/905870/122449052-bbaa8480-cfa5-11eb-8892-b51e7f1b5160.png)
final _m_ should be Grantha

and

`<seg function="blessing">ha<seg rend="grantha">riḥ</seg>`
is displayed
![image](https://user-images.githubusercontent.com/905870/122448778-69696380-cfa5-11eb-9b81-b38eb03b67bb.png)
_visarga_ should be fused with _ri_

**Comment by chchch** [comment]
Fixed! By the way you can get the oṃkāra sign ("ma" inside "o") by typing `oṁ` at the moment. It renders as `U+11350 GRANTHA OM`.
