### ISSUE TITLE
BnF Indien 294

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#59]
The `<pb>` import in the paratext display is the same almost everywhere (NB: this is a description lacking IIIF manifest and proper values for `@facs`, since the images are not yet delivered by BnF).
Possible to add a condition for export of `<pb @facs>` in paratext display, i.e., no export if there is no IIIF manifest?

**Comment by chchch** [comment]
If you remove the `@facs` attribute, it should work.

**Comment by manufrancis** [comment]
Hmm! But at some point of time I should add them again ;-).
I see that in this Indien 294 the value is always facs="0". Could it be an easy implemented condition for not exporting `<pb @facs>` in paratext display???

**Comment by chchch** [comment]
If we're waiting for images to come, maybe just leave it as `@facs=""` for now. The milestone will still be shown, but there won't be a link.

**Comment by manufrancis** [comment]
OK. Fine! In fact, the display is OK with `@facs="0`.
Au temps pour moi.
