### ISSUE TITLE
Indien 1036 blessing

### ISSUE THREAD

**Issue by chchch** [TST-Project/mss#61]
**śṟi**rāmajaya should be **śrī**rāmajaya (colphon, 94v3)

Can probably just tag the whole phrase as Sanskrit instead of just taggging the **ma** as grantha

**Comment by manufrancis** [comment]
Thanks! Corrected this typo!
As for full tagging as Sanskrit, the rā is an issue.

**Comment by chchch** [comment]
Ahh.. PS we have `<g ref="#double_kal">rā</g>` now...

**Comment by manufrancis** [comment]
Indeed! Updated in 1036!
