### ISSUE TITLE
Transcription button not working with <blockquote>

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#63]
See Indien 256
line 54 `<blockquote xml:lang="ta">`

![image](https://user-images.githubusercontent.com/905870/202905334-e662a6cb-e8a6-4530-a981-223c74e86f49.png)

**Comment by chchch** [comment]
Oh, `<blockquote>` is ILLEGAL(!!) in TEI. We can use `<q rend="block">` or `<quote rend="block">` instead.

**Comment by manufrancis** [comment]
Noted. Thanks!
