### ISSUE TITLE
seg rend=grantha

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#64]
Presently the words tagged `<seg rend="grantha">` are displayed in the catalogue as paratexts.

See e.g. Indien 545d:
 
![image](https://user-images.githubusercontent.com/905870/224038740-47e8482e-f6ec-420e-bb95-9b0008a3dc26.png)

Could you modify the code so that words tagged `<seg rend="grantha">` are not displayed in the catalogue as paratexts.

OR maybe we should tag differently words and letters in Grantha?
In DHARMA, we tag them `<hi rend="grantha">`.
We could also use the tag `<g>` but it means that we need to tag all the letters of the word.

Anu suggestions?

**Comment by chchch** [comment]
Ok I think I fixed it. I guess `<seg rend="grantha">` is ok for now?

**Comment by manufrancis** [comment]
Yes! It looks fine now. Thanks!
