### ISSUE TITLE
column "placement" in the the website paratexts tables 

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/mss#67]
The info in “placement” column is incorrect, see e.g.

![image](https://user-images.githubusercontent.com/905870/233085148-9d704883-9bd0-4d68-a7e4-230958df85ca.png)

It seems that the last `<lb>` before `<seg>` is displayed.

Note that most `<milestone unit="left-margin">` have been changed to `<fw>` and that most `<milestone unit="main-text-area">` have been deleted.

**Comment by chchch** [comment]
Should be fixed now.

**Comment by manufrancis** [comment]
Thanks!
